#!/bin/bash
set -e

COMMAND="$1"

show_help() {
  echo "Usage: gh hf <command>"
  echo
  echo "Commands:"
  echo "  enable"
  echo "    Add 'hacktoberfest' to repo topic and create the following labels"
  echo "    on the current repository: 'hacktoberfest', 'up-for-grabs'."
}

case "$COMMAND" in
  "enable")
    echo '>> Updating repository topics...'
    gh api '/repos/{owner}/{repo}/topics' --preview=mercy --jq='.names = (.names + ["hacktoberfest"] | unique)' \
      | gh api -X PUT '/repos/{owner}/{repo}/topics' --preview=mercy --input=-

    echo '>> Updating repository labels...'
    gh api '/repos/{owner}/{repo}/labels/hacktoberfest' >/dev/null 2>&1 \
      || (echo '{"name":"hacktoberfest","color":"f74700"}' | gh api -X POST '/repos/{owner}/{repo}/labels' --input=-)
    gh api '/repos/{owner}/{repo}/labels/up-for-grabs' >/dev/null 2>&1 \
      || (echo '{"name":"up-for-grabs","color":"009800"}' | gh api -X POST '/repos/{owner}/{repo}/labels' --input=-)
    ;;
  *)
    show_help
    ;;
esac