#!/bin/bash
set -e

COMMAND="$1"

show_help() {
  echo "Usage: gh hf <command>"
  echo
  echo "Commands:"
  echo "  enable"
  echo "    Add 'hacktoberfest' to repo topic and create the label 'hacktoberfest'."
}

case "$COMMAND" in
  "enable")
    echo '>> Updating repository topics...'
    gh api '/repos/{owner}/{repo}/topics' --preview=mercy --jq='.names = (.names + ["hacktoberfest"] | unique)' \
      | gh api -X PUT '/repos/{owner}/{repo}/topics' --preview=mercy --input=-

    echo '>> Updating repository labels...'
    gh api '/repos/{owner}/{repo}/labels/hacktoberfest' \
      || (echo '{"name":"hacktoberfest","color":"f74700"}' | gh api -X POST '/repos/{owner}/{repo}/labels' --input=-)
    ;;
  *)
    show_help
    ;;
esac